// flow-typed signature: 7741482ac76141fd0024f4fee6b7878c
// flow-typed version: <<STUB>>/redux-vanilla_v^0.0.1-beta1/flow_v0.69.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'redux-vanilla'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'redux-vanilla' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'redux-vanilla/example/src/App' {
  declare module.exports: any;
}

declare module 'redux-vanilla/example/src/App.test' {
  declare module.exports: any;
}

declare module 'redux-vanilla/example/src/index' {
  declare module.exports: any;
}

declare module 'redux-vanilla/example/src/registerServiceWorker' {
  declare module.exports: any;
}

declare module 'redux-vanilla/example/src/src/connect' {
  declare module.exports: any;
}

declare module 'redux-vanilla/example/src/src/connect.test' {
  declare module.exports: any;
}

declare module 'redux-vanilla/example/src/src/index' {
  declare module.exports: any;
}

declare module 'redux-vanilla/example/src/src/index.test' {
  declare module.exports: any;
}

declare module 'redux-vanilla/example/src/src/Provider' {
  declare module.exports: any;
}

declare module 'redux-vanilla/example/src/src/Provider.test' {
  declare module.exports: any;
}

declare module 'redux-vanilla/example/src/src/testutils' {
  declare module.exports: any;
}

declare module 'redux-vanilla/flow-typed/npm/babel-cli_vx.x.x' {
  declare module.exports: any;
}

declare module 'redux-vanilla/flow-typed/npm/babel-core_vx.x.x' {
  declare module.exports: any;
}

declare module 'redux-vanilla/flow-typed/npm/babel-eslint_vx.x.x' {
  declare module.exports: any;
}

declare module 'redux-vanilla/flow-typed/npm/babel-jest_vx.x.x' {
  declare module.exports: any;
}

declare module 'redux-vanilla/flow-typed/npm/babel-plugin-external-helpers_vx.x.x' {
  declare module.exports: any;
}

declare module 'redux-vanilla/flow-typed/npm/babel-plugin-transform-class-properties_vx.x.x' {
  declare module.exports: any;
}

declare module 'redux-vanilla/flow-typed/npm/babel-preset-env_vx.x.x' {
  declare module.exports: any;
}

declare module 'redux-vanilla/flow-typed/npm/babel-preset-react_vx.x.x' {
  declare module.exports: any;
}

declare module 'redux-vanilla/flow-typed/npm/codecov_vx.x.x' {
  declare module.exports: any;
}

declare module 'redux-vanilla/flow-typed/npm/eslint_vx.x.x' {
  declare module.exports: any;
}

declare module 'redux-vanilla/flow-typed/npm/eslint-plugin-prettier_vx.x.x' {
  declare module.exports: any;
}

declare module 'redux-vanilla/flow-typed/npm/eslint-plugin-react_vx.x.x' {
  declare module.exports: any;
}

declare module 'redux-vanilla/flow-typed/npm/flow-bin_v0.x.x' {
  declare module.exports: any;
}

declare module 'redux-vanilla/flow-typed/npm/flow-copy-source_vx.x.x' {
  declare module.exports: any;
}

declare module 'redux-vanilla/flow-typed/npm/jest_v22.x.x' {
  declare module.exports: any;
}

declare module 'redux-vanilla/flow-typed/npm/prettier_v1.x.x' {
  declare module.exports: any;
}

declare module 'redux-vanilla/flow-typed/npm/prop-types_v15.x.x' {
  declare module.exports: any;
}

declare module 'redux-vanilla/flow-typed/npm/redux_v3.x.x' {
  declare module.exports: any;
}

declare module 'redux-vanilla/flow-typed/npm/regenerator-runtime_vx.x.x' {
  declare module.exports: any;
}

declare module 'redux-vanilla/flow-typed/npm/rollup_vx.x.x' {
  declare module.exports: any;
}

declare module 'redux-vanilla/flow-typed/npm/rollup-plugin-babel_vx.x.x' {
  declare module.exports: any;
}

declare module 'redux-vanilla/flow-typed/npm/rollup-plugin-commonjs_vx.x.x' {
  declare module.exports: any;
}

declare module 'redux-vanilla/flow-typed/npm/rollup-plugin-flow_vx.x.x' {
  declare module.exports: any;
}

declare module 'redux-vanilla/flow-typed/npm/rollup-plugin-node-resolve_vx.x.x' {
  declare module.exports: any;
}

declare module 'redux-vanilla/flow-typed/npm/rollup-plugin-uglify_vx.x.x' {
  declare module.exports: any;
}

declare module 'redux-vanilla/jestSetup' {
  declare module.exports: any;
}

declare module 'redux-vanilla/lib/index' {
  declare module.exports: any;
}

declare module 'redux-vanilla/rollup.config' {
  declare module.exports: any;
}

declare module 'redux-vanilla/src/connect' {
  declare module.exports: any;
}

declare module 'redux-vanilla/src/connect.test' {
  declare module.exports: any;
}

declare module 'redux-vanilla/src/index' {
  declare module.exports: any;
}

declare module 'redux-vanilla/src/index.test' {
  declare module.exports: any;
}

declare module 'redux-vanilla/src/Provider' {
  declare module.exports: any;
}

declare module 'redux-vanilla/src/Provider.test' {
  declare module.exports: any;
}

declare module 'redux-vanilla/src/testutils' {
  declare module.exports: any;
}

// Filename aliases
declare module 'redux-vanilla/example/src/App.js' {
  declare module.exports: $Exports<'redux-vanilla/example/src/App'>;
}
declare module 'redux-vanilla/example/src/App.test.js' {
  declare module.exports: $Exports<'redux-vanilla/example/src/App.test'>;
}
declare module 'redux-vanilla/example/src/index.js' {
  declare module.exports: $Exports<'redux-vanilla/example/src/index'>;
}
declare module 'redux-vanilla/example/src/registerServiceWorker.js' {
  declare module.exports: $Exports<'redux-vanilla/example/src/registerServiceWorker'>;
}
declare module 'redux-vanilla/example/src/src/connect.js' {
  declare module.exports: $Exports<'redux-vanilla/example/src/src/connect'>;
}
declare module 'redux-vanilla/example/src/src/connect.test.js' {
  declare module.exports: $Exports<'redux-vanilla/example/src/src/connect.test'>;
}
declare module 'redux-vanilla/example/src/src/index.js' {
  declare module.exports: $Exports<'redux-vanilla/example/src/src/index'>;
}
declare module 'redux-vanilla/example/src/src/index.test.js' {
  declare module.exports: $Exports<'redux-vanilla/example/src/src/index.test'>;
}
declare module 'redux-vanilla/example/src/src/Provider.js' {
  declare module.exports: $Exports<'redux-vanilla/example/src/src/Provider'>;
}
declare module 'redux-vanilla/example/src/src/Provider.test.js' {
  declare module.exports: $Exports<'redux-vanilla/example/src/src/Provider.test'>;
}
declare module 'redux-vanilla/example/src/src/testutils.js' {
  declare module.exports: $Exports<'redux-vanilla/example/src/src/testutils'>;
}
declare module 'redux-vanilla/flow-typed/npm/babel-cli_vx.x.x.js' {
  declare module.exports: $Exports<'redux-vanilla/flow-typed/npm/babel-cli_vx.x.x'>;
}
declare module 'redux-vanilla/flow-typed/npm/babel-core_vx.x.x.js' {
  declare module.exports: $Exports<'redux-vanilla/flow-typed/npm/babel-core_vx.x.x'>;
}
declare module 'redux-vanilla/flow-typed/npm/babel-eslint_vx.x.x.js' {
  declare module.exports: $Exports<'redux-vanilla/flow-typed/npm/babel-eslint_vx.x.x'>;
}
declare module 'redux-vanilla/flow-typed/npm/babel-jest_vx.x.x.js' {
  declare module.exports: $Exports<'redux-vanilla/flow-typed/npm/babel-jest_vx.x.x'>;
}
declare module 'redux-vanilla/flow-typed/npm/babel-plugin-external-helpers_vx.x.x.js' {
  declare module.exports: $Exports<'redux-vanilla/flow-typed/npm/babel-plugin-external-helpers_vx.x.x'>;
}
declare module 'redux-vanilla/flow-typed/npm/babel-plugin-transform-class-properties_vx.x.x.js' {
  declare module.exports: $Exports<'redux-vanilla/flow-typed/npm/babel-plugin-transform-class-properties_vx.x.x'>;
}
declare module 'redux-vanilla/flow-typed/npm/babel-preset-env_vx.x.x.js' {
  declare module.exports: $Exports<'redux-vanilla/flow-typed/npm/babel-preset-env_vx.x.x'>;
}
declare module 'redux-vanilla/flow-typed/npm/babel-preset-react_vx.x.x.js' {
  declare module.exports: $Exports<'redux-vanilla/flow-typed/npm/babel-preset-react_vx.x.x'>;
}
declare module 'redux-vanilla/flow-typed/npm/codecov_vx.x.x.js' {
  declare module.exports: $Exports<'redux-vanilla/flow-typed/npm/codecov_vx.x.x'>;
}
declare module 'redux-vanilla/flow-typed/npm/eslint_vx.x.x.js' {
  declare module.exports: $Exports<'redux-vanilla/flow-typed/npm/eslint_vx.x.x'>;
}
declare module 'redux-vanilla/flow-typed/npm/eslint-plugin-prettier_vx.x.x.js' {
  declare module.exports: $Exports<'redux-vanilla/flow-typed/npm/eslint-plugin-prettier_vx.x.x'>;
}
declare module 'redux-vanilla/flow-typed/npm/eslint-plugin-react_vx.x.x.js' {
  declare module.exports: $Exports<'redux-vanilla/flow-typed/npm/eslint-plugin-react_vx.x.x'>;
}
declare module 'redux-vanilla/flow-typed/npm/flow-bin_v0.x.x.js' {
  declare module.exports: $Exports<'redux-vanilla/flow-typed/npm/flow-bin_v0.x.x'>;
}
declare module 'redux-vanilla/flow-typed/npm/flow-copy-source_vx.x.x.js' {
  declare module.exports: $Exports<'redux-vanilla/flow-typed/npm/flow-copy-source_vx.x.x'>;
}
declare module 'redux-vanilla/flow-typed/npm/jest_v22.x.x.js' {
  declare module.exports: $Exports<'redux-vanilla/flow-typed/npm/jest_v22.x.x'>;
}
declare module 'redux-vanilla/flow-typed/npm/prettier_v1.x.x.js' {
  declare module.exports: $Exports<'redux-vanilla/flow-typed/npm/prettier_v1.x.x'>;
}
declare module 'redux-vanilla/flow-typed/npm/prop-types_v15.x.x.js' {
  declare module.exports: $Exports<'redux-vanilla/flow-typed/npm/prop-types_v15.x.x'>;
}
declare module 'redux-vanilla/flow-typed/npm/redux_v3.x.x.js' {
  declare module.exports: $Exports<'redux-vanilla/flow-typed/npm/redux_v3.x.x'>;
}
declare module 'redux-vanilla/flow-typed/npm/regenerator-runtime_vx.x.x.js' {
  declare module.exports: $Exports<'redux-vanilla/flow-typed/npm/regenerator-runtime_vx.x.x'>;
}
declare module 'redux-vanilla/flow-typed/npm/rollup_vx.x.x.js' {
  declare module.exports: $Exports<'redux-vanilla/flow-typed/npm/rollup_vx.x.x'>;
}
declare module 'redux-vanilla/flow-typed/npm/rollup-plugin-babel_vx.x.x.js' {
  declare module.exports: $Exports<'redux-vanilla/flow-typed/npm/rollup-plugin-babel_vx.x.x'>;
}
declare module 'redux-vanilla/flow-typed/npm/rollup-plugin-commonjs_vx.x.x.js' {
  declare module.exports: $Exports<'redux-vanilla/flow-typed/npm/rollup-plugin-commonjs_vx.x.x'>;
}
declare module 'redux-vanilla/flow-typed/npm/rollup-plugin-flow_vx.x.x.js' {
  declare module.exports: $Exports<'redux-vanilla/flow-typed/npm/rollup-plugin-flow_vx.x.x'>;
}
declare module 'redux-vanilla/flow-typed/npm/rollup-plugin-node-resolve_vx.x.x.js' {
  declare module.exports: $Exports<'redux-vanilla/flow-typed/npm/rollup-plugin-node-resolve_vx.x.x'>;
}
declare module 'redux-vanilla/flow-typed/npm/rollup-plugin-uglify_vx.x.x.js' {
  declare module.exports: $Exports<'redux-vanilla/flow-typed/npm/rollup-plugin-uglify_vx.x.x'>;
}
declare module 'redux-vanilla/jestSetup.js' {
  declare module.exports: $Exports<'redux-vanilla/jestSetup'>;
}
declare module 'redux-vanilla/lib/index.js' {
  declare module.exports: $Exports<'redux-vanilla/lib/index'>;
}
declare module 'redux-vanilla/rollup.config.js' {
  declare module.exports: $Exports<'redux-vanilla/rollup.config'>;
}
declare module 'redux-vanilla/src/connect.js' {
  declare module.exports: $Exports<'redux-vanilla/src/connect'>;
}
declare module 'redux-vanilla/src/connect.test.js' {
  declare module.exports: $Exports<'redux-vanilla/src/connect.test'>;
}
declare module 'redux-vanilla/src/index.js' {
  declare module.exports: $Exports<'redux-vanilla/src/index'>;
}
declare module 'redux-vanilla/src/index.test.js' {
  declare module.exports: $Exports<'redux-vanilla/src/index.test'>;
}
declare module 'redux-vanilla/src/Provider.js' {
  declare module.exports: $Exports<'redux-vanilla/src/Provider'>;
}
declare module 'redux-vanilla/src/Provider.test.js' {
  declare module.exports: $Exports<'redux-vanilla/src/Provider.test'>;
}
declare module 'redux-vanilla/src/testutils.js' {
  declare module.exports: $Exports<'redux-vanilla/src/testutils'>;
}
